/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Pais;

/**
 *
 * @author Iván González
 */
public class DiaModificarPais extends javax.swing.JDialog {

    private Pais pais;

    /**
     * Creates new form DiaModificarPais
     */
    public DiaModificarPais(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DiaModificarPais(java.awt.Frame parent, boolean modal, Pais pais) {
        super(parent, modal);
        this.pais = pais;
        initComponents();
        cargarDatos();
        setLocationRelativeTo(this);
    }

    private void cargarDatos() {
        txtNombre.setText(pais.getNombre());
        txtCapital.setText(pais.getCapital());
        txtTerritorio.setText(pais.getTerritorio().toString());
        txtPIB.setText(pais.getPib().toString());
    }

    private void guardarDatos() {
        try {
            pais.setNombre(txtNombre.getText());
            pais.setCapital(txtCapital.getText());
            pais.setTerritorio(Double.parseDouble(txtTerritorio.getText()));
            pais.setPib(Double.parseDouble(txtPIB.getText()));
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, "Valor en Territorio o PIB incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCapital = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTerritorio = new javax.swing.JTextField();
        txtPIB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar País");

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información País"));
        jPanel2.setLayout(null);

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 30);

        txtNombre.setText("jTextField1");
        jPanel2.add(txtNombre);
        txtNombre.setBounds(90, 20, 180, 30);

        txtCapital.setText("jTextField1");
        jPanel2.add(txtCapital);
        txtCapital.setBounds(90, 60, 180, 30);

        jLabel2.setText("Capital:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 70, 30);

        jLabel3.setText("Territorio:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 100, 70, 30);

        txtTerritorio.setText("jTextField1");
        jPanel2.add(txtTerritorio);
        txtTerritorio.setBounds(90, 100, 180, 30);

        txtPIB.setText("jTextField1");
        jPanel2.add(txtPIB);
        txtPIB.setBounds(90, 140, 180, 30);

        jLabel4.setText("PIB:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 140, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 290, 180);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(210, 190, 90, 22);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(110, 190, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        guardarDatos();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaModificarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaModificarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaModificarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaModificarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaModificarPais dialog = new DiaModificarPais(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtTerritorio;
    // End of variables declaration//GEN-END:variables
}
