/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.PaisController;
import controlador.grafo.Grafo;
import controlador.lista.ListaEnlazada;
import controlador.utilidades.Utilidades;
import java.awt.List;
import javax.swing.JOptionPane;
import vista.modeloTabla.ModeloTablaRutas;

/**
 *
 * @author Iván González
 */
public class DiaRutas extends javax.swing.JDialog {

    private ModeloTablaRutas modeloTablaRutas = new ModeloTablaRutas();
    private FrmGrafo frmGrafo;
    private PaisController paisController;
    private Grafo grafo;

    /**
     * Creates new form DiaRutas
     */
    public DiaRutas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DiaRutas(java.awt.Frame parent, boolean modal, PaisController paisController) {
        super(parent, modal);
        this.paisController = paisController;
        this.grafo = paisController.getGrafo();
        initComponents();
        cargarCombos();
        cargarTabla();
        setLocationRelativeTo(this);
    }

    private void cargarCombos() {
        try {
            Utilidades.cargarComboPais(cbxPaisOrigen, paisController);
            Utilidades.cargarComboPais(cbxPaisDestino, paisController);
        } catch (Exception e) {
            System.out.println("Error al cargar los comboBox " + e);
        }
    }

    private void cargarTabla() {
        modeloTablaRutas.setGnde(paisController.getGrafo());
        tblRutas.setModel(modeloTablaRutas);
        modeloTablaRutas.fireTableStructureChanged();
        tblRutas.updateUI();
    }

    private void fijarRuta() {
        Integer inicio = cbxPaisOrigen.getSelectedIndex();
        Integer destino = cbxPaisDestino.getSelectedIndex();
        if (inicio == destino) {
            JOptionPane.showMessageDialog(null, "No escoger el mismo país", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                paisController.getGrafo().insertarArista(inicio + 1, destino + 1, Double.parseDouble(txtDistancia.getText()));
                cargarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxPaisOrigen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxPaisDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        btnAgregarRuta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRutas = new javax.swing.JTable();
        btnVerGrafo = new javax.swing.JButton();
        btnDijkstra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCaminoMinimo = new javax.swing.JTextArea();
        btnFloyd = new javax.swing.JButton();
        btnRecorridoAnchura = new javax.swing.JButton();
        btnRecorridoProfundidad = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rutas");

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rutas"));
        jPanel2.setLayout(null);

        jLabel1.setText("Distancia(km):");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(290, 20, 100, 30);

        cbxPaisOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxPaisOrigen);
        cbxPaisOrigen.setBounds(110, 20, 150, 30);

        jLabel2.setText("Pais Destino:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 100, 30);

        cbxPaisDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxPaisDestino);
        cbxPaisDestino.setBounds(110, 60, 150, 30);

        jLabel3.setText("Pais Origen:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 100, 30);
        jPanel2.add(txtDistancia);
        txtDistancia.setBounds(390, 20, 150, 30);

        btnAgregarRuta.setText("Agregar Ruta");
        btnAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRutaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarRuta);
        btnAgregarRuta.setBounds(340, 60, 160, 22);

        tblRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRutas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 540, 220);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 0, 560, 330);

        btnVerGrafo.setText("VER GRAFO");
        btnVerGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerGrafo);
        btnVerGrafo.setBounds(50, 490, 140, 22);

        btnDijkstra.setText("Dijkstra");
        btnDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDijkstraActionPerformed(evt);
            }
        });
        jPanel1.add(btnDijkstra);
        btnDijkstra.setBounds(30, 380, 180, 22);

        txtCaminoMinimo.setEditable(false);
        txtCaminoMinimo.setColumns(20);
        txtCaminoMinimo.setRows(5);
        jScrollPane2.setViewportView(txtCaminoMinimo);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(260, 360, 290, 180);

        btnFloyd.setText("Floyd");
        btnFloyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloydActionPerformed(evt);
            }
        });
        jPanel1.add(btnFloyd);
        btnFloyd.setBounds(30, 350, 180, 22);

        btnRecorridoAnchura.setText("Recorrido Anchura");
        btnRecorridoAnchura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoAnchuraActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecorridoAnchura);
        btnRecorridoAnchura.setBounds(30, 420, 180, 22);

        btnRecorridoProfundidad.setText("Recorrido Profundidad");
        btnRecorridoProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoProfundidadActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecorridoProfundidad);
        btnRecorridoProfundidad.setBounds(30, 450, 180, 22);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(70, 530, 100, 22);

        jLabel4.setText("CAMINO DIJKSTRA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 340, 120, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRutaActionPerformed
        // TODO add your handling code here:
        fijarRuta();
        txtDistancia.setText("");
    }//GEN-LAST:event_btnAgregarRutaActionPerformed

    private void btnVerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGrafoActionPerformed
        // TODO add your handling code here:
        frmGrafo = new FrmGrafo(null, true, paisController.getGrafo(), 1);
        frmGrafo.setVisible(true);
//        paisController.getGrafo().caminoMinimoDijkstra(cbxPaisOrigen.getSelectedIndex()+1).imprimir();
    }//GEN-LAST:event_btnVerGrafoActionPerformed

    private void btnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkstraActionPerformed
        // TODO add your handling code here:
//        paisController.getGrafo().caminoMinimoDijkstra(cbxPaisOrigen.getSelectedIndex() + 1);
//        System.out.println(cbxPaisOrigen.getSelectedItem().toString());
        txtCaminoMinimo.setText("");
        StringBuilder texto = new StringBuilder(txtCaminoMinimo.getText());
        texto.append(" Origen: " + cbxPaisOrigen.getSelectedItem().toString() + "\n");
        texto.append(" -------------------\n");
        try {
            for (int i = 0; i < paisController.getGrafo().numVertices(); i++) {
//                txtCaminoMinimo.setText(cbxPaisOrigen.getSelectedItem().toString() + "\n" +
//                        paisController.getGrafo().obtenerEtiqueta(i+1) + " - " + paisController.getGrafo().caminoMinimoDijkstra(cbxPaisOrigen.getSelectedIndex() + 1).obtener(i));
                texto.append( " " + (i+1) + ". " + paisController.getGrafo().obtenerEtiqueta(i+1) + " - " + paisController.getGrafo().caminoMinimoDijkstra(cbxPaisOrigen.getSelectedIndex() + 1).obtener(i) + "\n");
//                System.out.println("Vertice " + paisController.getGrafo().obtenerEtiqueta(i+1) + " - " + paisController.getGrafo().caminoMinimoDijkstra(cbxPaisOrigen.getSelectedIndex() + 1).obtener(i));
            }
            txtCaminoMinimo.setText(texto.toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDijkstraActionPerformed

    private void btnFloydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloydActionPerformed
        // TODO add your handling code here:
        DiaCaminoFloyd diaCaminoFloyd = new DiaCaminoFloyd(null, true, paisController);
        diaCaminoFloyd.setVisible(true);
    }//GEN-LAST:event_btnFloydActionPerformed

    private void btnRecorridoAnchuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoAnchuraActionPerformed
        // TODO add your handling code here:
        ListaEnlazada lista = new ListaEnlazada();
        try {
            lista = paisController.getGrafo().recorridoPrimeroAnchura(cbxPaisOrigen.getSelectedIndex() + 1);
        } catch (Exception e) {
            System.out.println("Error al ejecutar la busqueda en anchura: " + e);
        }
        DiaRecorridos diaRecorridoAnchura = new DiaRecorridos(null, true, paisController, lista);
        diaRecorridoAnchura.setVisible(true);
    }//GEN-LAST:event_btnRecorridoAnchuraActionPerformed

    private void btnRecorridoProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoProfundidadActionPerformed
        // TODO add your handling code here:
        ListaEnlazada lista = new ListaEnlazada();
        
        try {
            lista = paisController.getGrafo().recorridoPrimeroProfundidad(cbxPaisOrigen.getSelectedIndex() + 1);
        } catch (Exception e) {
            System.out.println("Error al ejecutrar la busqueda en profundidad: " + e);
        }
        DiaRecorridos diaRecorridos = new DiaRecorridos(null, true, paisController, lista);
        diaRecorridos.setVisible(true);
    }//GEN-LAST:event_btnRecorridoProfundidadActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaRutas dialog = new DiaRutas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRuta;
    private javax.swing.JButton btnDijkstra;
    private javax.swing.JButton btnFloyd;
    private javax.swing.JButton btnRecorridoAnchura;
    private javax.swing.JButton btnRecorridoProfundidad;
    private javax.swing.JButton btnVerGrafo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxPaisDestino;
    private javax.swing.JComboBox<String> cbxPaisOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRutas;
    private javax.swing.JTextArea txtCaminoMinimo;
    private javax.swing.JTextField txtDistancia;
    // End of variables declaration//GEN-END:variables
}
