/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PaisController;
import controlador.lista.ListaEnlazada;
import controlador.utilidades.Utilidades;
import javax.swing.JOptionPane;
import modelo.Pais;
import vista.modeloTabla.ModeloTablaPais;

/**
 *
 * @author Iván González
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private PaisController paisController = new PaisController();
//    private ListaEnlazada<Pais> paises = new ListaEnlazada<>();
    private ModeloTablaPais mtp = new ModeloTablaPais();
    private DiaModificarPais diaModificarPais;
    private DiaRutas diaRutas;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarTabla();
        try {
            cargarJson();
        } catch (Exception e) {
            System.out.println("Error cargando el json: " + e);
        }
        setLocationRelativeTo(this);
    }
    
    private void cargarJson(){
        if(Utilidades.cargarJson() != null){
            paisController.setPaises(Utilidades.cargarJson().getPaises());
            paisController.getPaises().imprimir();
            cargarTabla();
        }
    }

    private void limpiar() {
        txtNombre.setText("");
        txtCapital.setText("");
        txtTerritorio.setText("");
        txtPIB.setText("");
    }

    private void cargarTabla() {
        mtp.setPaises(paisController.getPaises());
        tblPaises.setModel(mtp);
        tblPaises.updateUI();
        limpiar();
    }

    private void agregarPais() {
        if (txtNombre.getText().isEmpty() || txtCapital.getText().isEmpty() || txtTerritorio.getText().isEmpty() || txtPIB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Pais p = new Pais();
                p.setId(paisController.getPaises().getSize() + 1);
                p.setNombre(txtNombre.getText());
                p.setCapital(txtCapital.getText());
                p.setTerritorio(Double.parseDouble(txtTerritorio.getText()));
                p.setPib(Double.parseDouble(txtPIB.getText()));
                paisController.getPaises().insertar(p);
                Utilidades.guardarJson(paisController);
                cargarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Valor en Territorio o PIB incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCapital = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTerritorio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        btnAgregarPais = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaises = new javax.swing.JTable();
        btnVerGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Países");
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información País"));
        jPanel2.setLayout(null);

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 70, 30);

        txtNombre.setText("jTextField1");
        jPanel2.add(txtNombre);
        txtNombre.setBounds(90, 30, 180, 30);

        jLabel2.setText("Capital:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 70, 30);

        txtCapital.setText("jTextField1");
        jPanel2.add(txtCapital);
        txtCapital.setBounds(90, 70, 180, 30);

        jLabel3.setText("Territorio:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 70, 30);

        txtTerritorio.setText("jTextField1");
        jPanel2.add(txtTerritorio);
        txtTerritorio.setBounds(90, 110, 180, 30);

        jLabel4.setText("PIB(Mill):");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 150, 70, 30);

        txtPIB.setText("jTextField1");
        jPanel2.add(txtPIB);
        txtPIB.setBounds(90, 150, 180, 30);

        btnAgregarPais.setText("Agregar");
        btnAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPaisActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarPais);
        btnAgregarPais.setBounds(150, 190, 100, 22);

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar);
        btncancelar.setBounds(30, 190, 100, 22);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar);
        btnModificar.setBounds(30, 220, 100, 22);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(150, 220, 100, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 280, 250);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Países"));
        jPanel3.setLayout(null);

        tblPaises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPaises);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 400, 220);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(290, 10, 420, 250);

        btnVerGrafo.setText("AGREGAR RUTAS");
        btnVerGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerGrafo);
        btnVerGrafo.setBounds(520, 260, 180, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPaisActionPerformed
        // TODO add your handling code here:
        agregarPais();
    }//GEN-LAST:event_btnAgregarPaisActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (tblPaises.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un país de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                diaModificarPais = new DiaModificarPais(this, true, paisController.getPaises().obtener(tblPaises.getSelectedRow()));
                diaModificarPais.setVisible(true);
                Utilidades.guardarJson(paisController);
                cargarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (tblPaises.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un país de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Integer i = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que quiere eliminar el arbol?");
            if (i == JOptionPane.OK_OPTION) {
                try {
                    paisController.getPaises().eliminar(tblPaises.getSelectedRow());
                    Utilidades.guardarJson(paisController);
                    cargarTabla();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGrafoActionPerformed
        // TODO add your handling code here:
        if(paisController.getGrafo() != null){
            diaRutas = new DiaRutas(this, true, paisController);
            diaRutas.setVisible(true);
        }
    }//GEN-LAST:event_btnVerGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPais;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVerGrafo;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPaises;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtTerritorio;
    // End of variables declaration//GEN-END:variables
}
